#!/bin/sh
# Prepare a box to run the SwasthaSetu pilot.
#
# Writes .env.pilot with real secrets. Run once, then:
#   docker compose --profile quick up --build
set -eu

ENV_FILE=".env.pilot"

if [ ! -f "docker-compose.yml" ]; then
  echo "Run this from the repository root (where docker-compose.yml lives)." >&2
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required to generate secrets but was not found." >&2
  echo "  Debian/Ubuntu: sudo apt-get install openssl" >&2
  echo "  macOS:         already present, or brew install openssl" >&2
  exit 1
fi

# Refusing rather than overwriting is deliberate. Rotating
# FIELD_ENCRYPTION_KEY makes every result value already written to the pilot
# database permanently unreadable, and AUTH_SECRET invalidates live sessions
# and every issued tracking link.
if [ -f "${ENV_FILE}" ]; then
  echo "${ENV_FILE} already exists — leaving it untouched." >&2
  echo >&2
  echo "Regenerating its keys would make results already encrypted in the" >&2
  echo "pilot database unreadable. To start genuinely fresh, remove both the" >&2
  echo "file and the volume:" >&2
  echo >&2
  echo "  rm ${ENV_FILE} && docker compose down -v" >&2
  exit 1
fi

# -base64 wraps at 64 columns; strip any newline so the value stays on one line.
AUTH_SECRET="$(openssl rand -base64 48 | tr -d '\n')"
FIELD_ENCRYPTION_KEY="$(openssl rand -hex 32 | tr -d '\n')"

cat > "${ENV_FILE}" <<EOF
# SwasthaSetu pilot configuration. Generated by scripts/pilot-setup.sh.
#
# NEVER COMMIT THIS FILE. It is covered by .gitignore and .dockerignore.
#
# Every integration below runs against a working simulator until you supply
# its credentials. Adding a key switches that one integration to live and
# needs only a restart — lib/env.ts reads all of these at runtime, so there
# is no rebuild:
#
#   docker compose --profile named up -d --force-recreate app

# --- security (generated; do not rotate mid-pilot) --------------------------
AUTH_SECRET="${AUTH_SECRET}"
FIELD_ENCRYPTION_KEY="${FIELD_ENCRYPTION_KEY}"

# --- Cloudflare named tunnel ------------------------------------------------
# From the Zero Trust dashboard: Networks -> Tunnels -> Create a tunnel.
# Required for the --profile named stack, which is what a real pilot wants:
# the quick tunnel's hostname changes on every restart and would silently
# break the Razorpay webhook you registered against it.
# TUNNEL_TOKEN=

# --- demo data --------------------------------------------------------------
# Seeds a zone, three partner labs and twelve families on first boot only.
# Set to false to start empty for a pilot with real labs and real families.
PILOT_SEED_DEMO_DATA=true

# --- Razorpay (UPI Autopay, cards, netbanking) ------------------------------
# Webhook URL: https://<your-tunnel-hostname>/api/payments/webhook
# Subscribe to: payment.captured, payment.failed, subscription.activated,
# subscription.charged, subscription.halted, subscription.cancelled
# RAZORPAY_KEY_ID=
# RAZORPAY_KEY_SECRET=
# RAZORPAY_WEBHOOK_SECRET=

# --- ElevenLabs (voice assistant) -------------------------------------------
# The agent already exists in the workspace. Every turn still passes through
# the server-side output guard in app/api/voice/turn/route.ts either way.
# ELEVENLABS_API_KEY=
# NEXT_PUBLIC_ELEVENLABS_AGENT_ID=agent_2901m1x6rwtxf4bs8yyz1836r85a

# --- Google Maps ------------------------------------------------------------
# Enable: Maps JavaScript API, Geocoding, Directions, Distance Matrix, Places.
# Restrict the public key by HTTP referrer to your tunnel hostname.
# NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=
# GOOGLE_MAPS_SERVER_KEY=

# --- SMS (real OTPs) --------------------------------------------------------
# Without these, OTP codes print to the container log:
#   docker compose logs -f app
# MSG91_AUTH_KEY=
# MSG91_SENDER_ID=

# --- ABDM / ABHA ------------------------------------------------------------
# Sandbox credentials from https://sandbox.abdm.gov.in. Production needs
# M1/M2/M3 certification — see docs/abdm-go-live.md.
ABDM_ENV="sandbox"
# ABDM_CLIENT_ID=
# ABDM_CLIENT_SECRET=

# --- retention & operating limits -------------------------------------------
PING_RETENTION_DAYS=30
TRANSCRIPT_RETENTION_DAYS=90
SAMPLE_CLOCK_MINUTES=120
EOF

chmod 600 "${ENV_FILE}"

echo "Wrote ${ENV_FILE} (mode 600) with freshly generated secrets."
echo
echo "Next:"
echo "  docker compose --profile quick up --build"
echo "  docker compose logs tunnel-quick | grep trycloudflare"
echo
echo "That prints an HTTPS URL. Open it on a phone — GPS and the microphone"
echo "work there and do not over plain HTTP, which is the point of the tunnel."
